RM-7463: The dismissal of "confirm" dialogs opened while inside an iframe throws a WebDriverException in Firefox
re-motion/Trunk-SVN2Git pull request #114
Opened 2020-08-04 12:57 UTC by iam-mholle

https://re-motion.atlassian.net/browse/RM-7463

2020-08-04 12:58 UTC, iam-mholle commented
Might be better to always use the Selenium solution.

2020-08-17 14:08 UTC, Stefan-Ilic requested changes

2020-08-27 14:40 UTC, iam-mholle commented on Remotion/Web/Development.WebTesting/ModalDialogHandlers/CancelModalDialogHandler.cs
> +        webDriver.SwitchTo().Alert().Dismiss();
Unfortunately, this seems like a forever fix.

2021-02-01 14:17 UTC, iam-mholle commented
Stale PR

2021-02-01 14:17 UTC, closed without merging