RM-7475: Focus before clicking in Firefox
re-motion/Trunk-SVN2Git pull request #119
Opened 2020-08-27 11:20 UTC by iam-mholle

https://re-motion.atlassian.net/browse/RM-7475

2020-08-27 11:22 UTC, Stefan-Ilic requested changes

2020-08-27 11:22 UTC, Stefan-Ilic commented on Remotion/Web/Development.WebTesting/WebTestActions/ClickAction.cs
> +      if (scope.Browser.IsFirefox() || scope.Browser.IsInternetExplorer())
Could you link the RM or Firefox issue here and indicate that this is a workaround?

2020-08-27 11:42 UTC, Stefan-Ilic requested changes

2020-08-27 11:42 UTC, Stefan-Ilic commented on Remotion/Web/Development.WebTesting/WebTestActions/ClickAction.cs
> +      // RM-7475: Workaround for Firefox not scrolling to buttons contained in an iframe outside of the viewport bounds
Could you unlink this? Thanks.

2020-08-27 11:44 UTC, Stefan-Ilic approved these changes

2020-08-31 10:15 UTC, MichaelKetting approved these changes

2020-09-02 08:08 UTC, iam-mholle commented
Added to master with 75b81a8dc35ea3c4cbd6314e5c247be8c643c7dd.

2020-09-02 08:08 UTC, closed without merging