RM-6664: Swallow postback requests triggered by double clicking a button or hyperlink
re-motion/Trunk-SVN2Git pull request #120
Opened 2020-08-31 09:27 UTC by iam-mholle

https://re-motion.atlassian.net/browse/RM-6664

2020-09-01 10:34 UTC, Stefan-Ilic approved these changes

2020-09-01 16:00 UTC, MichaelKetting requested changes

2020-09-02 07:59 UTC, iam-mholle commented on Remotion/Web/Core/Res/HTML/SmartPage.js
> +      if (tagName === 'a' || type === 'submit' || type === 'button')
Oh well, didn't know that - makes everything simpler tho, thanks for the explanation.

2020-09-02 08:54 UTC, MichaelKetting requested changes

2020-09-02 08:54 UTC, MichaelKetting commented on Remotion/Web/Core/Res/HTML/SmartPage.js
> +    else if (isAutoPostback || submitterElement.id !== _submitState.Submitter.id)
submitterElement can be null, see line 1151

2020-09-02 09:57 UTC, MichaelKetting approved these changes
I'm assuming this succeeded in a manual test. the code does look correct but I have learned to be careful in the web.

2020-09-03 10:38 UTC, iam-mholle commented
Added to master with be835625ea6356be219932d1a0520a6e28fe8d7e.

2020-09-03 10:38 UTC, closed without merging