RM-7504: Move BocAutoCompleteReference popup next to the button for opening the popup instead of the bottom of the body
re-motion/Trunk-SVN2Git pull request #128
Opened 2020-09-18 11:34 UTC by iam-mholle

https://re-motion.atlassian.net/browse/RM-7504

2020-09-21 13:13 UTC, dukorama approved these changes

2020-11-18 13:35 UTC, dukorama approved these changes

2020-11-25 09:58 UTC, MichaelKetting requested changes

2020-11-25 09:58 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/Res/HTML/BocAutoCompleteReferenceValue.jquery.js
> +            .appendTo($('#' + options.dropDownButtonID).closest('div, td, th, body'));
I think we should use $(input) to be more consistent with rest of the code.

2020-11-25 09:58 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/Res/HTML/BocAutoCompleteReferenceValue.jquery.js
> +            .appendTo($('#' + options.dropDownButtonID).closest('div, td, th, body'));
see above

2020-11-25 10:56 UTC, MichaelKetting approved these changes

2020-11-26 09:22 UTC, iam-mholle commented
Added to master with e29f539c48fd68076046c0c42038d4421e814eed.

2020-11-26 09:22 UTC, closed without merging