Catch and log InvalidOperationException while pulling Docker image
re-motion/Trunk-SVN2Git pull request #143
Opened 2020-11-16 09:42 UTC by raffaelfoidl

https://re-motion.atlassian.net/browse/RM-7530

2020-11-16 09:47 UTC, iam-mholle approved these changes

2020-11-16 12:21 UTC, MichaelKetting requested changes
This design uses the IDockerClient like a 3rd party API with a pre-defiend contract. We should consider a other design-options first before catching any and all InvalidOperationExceptions thrown by this code. Please make suggestions :)

2020-11-16 12:41 UTC, iam-mholle commented
> 
> 
> This design uses the IDockerClient like a 3rd party API with a pre-defiend contract. We should consider a other design-options first before catching any and all InvalidOperationExceptions thrown by this code. Please make suggestions :)

Valid point with the `InvalidOperationException`, the client should throw a more precise exception that can be caught. Apart from that, I don't really see the issue, retrying a pull/ignoring the error is not part of the responsibility of the simple `docker pull` abstraction the method represents, that's something the user of it should do. What about a decorator ignoring the error the pull throws?

2020-11-16 13:15 UTC, MichaelKetting commented
> 
> 
> > This design uses the IDockerClient like a 3rd party API with a pre-defiend contract. We should consider a other design-options first before catching any and all InvalidOperationExceptions thrown by this code. Please make suggestions :)
> 
> Valid point with the `InvalidOperationException`, the client should throw a more precise exception that can be caught. Apart from that, I don't really see the issue, retrying a pull/ignoring the error is not part of the responsibility of the simple `docker pull` abstraction the method represents, that's something the user of it should do. What about a decorator ignoring the error the pull throws?

re decorator: perhaps. 
custom exception: yes, that's one way to go.

I was also considering a result (success/failed) or a parameter (fail quietly). Sometimes, I'm still unmanaged C :D But yes, a custom excpetion is probably okay for this.

2020-11-17 11:43 UTC, MichaelKetting requested changes

2020-11-17 11:43 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting/HostingStrategies/DockerHosting/DockerClientException.cs
> +  public class DockerClientException : Exception
DockerOperationException, inlcude the result-code in the exception as separate field.

2020-11-17 11:43 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting/HostingStrategies/IisDockerContainerWrapper.cs
> +        s_log.Error ("Pulling docker image failed", ex);
log the image name. 
end sentence with a .
log fallback behavior.

2020-11-17 15:13 UTC, MichaelKetting approved these changes

2020-11-18 09:48 UTC, iam-mholle commented
Added to master with 03eba1708ba00b7b24c8e1ae31129a21b8d292df.

2020-11-18 09:48 UTC, closed without merging