Feature/firefox version upgrade 82
re-motion/Trunk-SVN2Git pull request #144
Opened 2020-11-20 10:42 UTC by raffaelfoidl

https://re-motion.atlassian.net/browse/RM-7519

2020-11-20 10:52 UTC, MichaelKetting requested changes
Merge after TeamCity okay's it.

2020-11-20 10:52 UTC, MichaelKetting approved these changes
Merge after Teamcity okay's it.

2020-11-23 09:27 UTC, Stefan-Ilic approved these changes

2020-11-30 11:43 UTC, raffaelfoidl commented
Added to master with a7d29c82482b7779d6dfa60a036a0268f3596145.

2020-11-30 11:43 UTC, closed without merging